### ISSUE TITLE
Add Stop/Pause to Shade Control Module

### ISSUE THREAD

**Issue by chazman88** [jbasen/Crestron-Hubitat-Integration#12]
Hi,

I use these modules in my own system and they work great. 
Ive modified the shade control module to have a stop command (for my shades I need to send "pause", not sure if this is the same for all shades)

THREADSAFE PUSH Shade_Stop
{
	Trace("Hubitat Shade-EventHandler-Shade_Stop\n");
	if (Startup_Lock = 2)
	{
		myHubitat.Send_Device_Command("command", "pause", "",  "", "", itoa(Device_ID), Auto_Refresh);
	}
}

Would you be interested in including this in the module to save me from having to edit it each time you issue and update?
Thanks
Charlie

**Comment by jbasen** [comment]
Thanks for the suggestion Charlie.  

I've included this in Hubitat code so the next time I upload a new version of the entire code set to GitHub it will be included.  FYI - I updated the version of the shade module from 2.3 to 2.4.  That way you will be able to just drag/drop the signals and parameters from the 2.3 module to the 2.4 module.  

Thanks again
