### ISSUE TITLE
Motion Module not triggering without refresh

### ISSUE THREAD

**Issue by chazman88** [jbasen/Crestron-Hubitat-Integration#13]
Hi,

Using these modules in my own system and have noticed that Motion 2.1 module has stopped automatically triggering into crestron. 

I do see motion active/inactive on the habitat dashboard, but have to refresh the crestron module to get the correct state. 
Never used to have to do this......

Any ideas?

**Comment by chazman88** [comment]
Looks like I may have had an erroneous space in the "URL to POST device events to"!!
🤦🏻‍♂️

**Comment by jbasen** [comment]
I’m glad the issue is resolved and thanks for following up and closing the thread
