### ISSUE TITLE
Shades: Stop

### ISSUE THREAD

**Issue by ZippoD** [jbasen/Crestron-Hubitat-Integration#14]
Hi Jay,
Do you have any shades connected to Hubitat?
I just tried to use Shade:Stop command and got an error. I noticed the generated URL has /device/##/pause?access_token. I copy and pasted in browsers and got 404. Replaced "pause" with open and was able to control the shade with this HTTP get command. That also loaded all the capabilities for this device - there is no pause command. 

So I wonder, if this [hubitat] device driver is the problem (lacking the stop/pause functionally), although it is built in and not custom. Please check if you have shades. Thanks.

**Comment by jbasen** [comment]
See if changing

myHubitat.Send_Device_Command("command", "pause", "", "", "", itoa(Device_ID), Auto_Refresh);

to

myHubitat.Send_Device_Command("command", "stopPositionChange", "", "", "", itoa(Device_ID), Auto_Refresh);

in the Hubitat Shade v3.usp module will fix the problem for you.

Thanks

**Comment by ZippoD** [comment]
That will likely do it, as there is "stopPositionChange" function in Hubitat. That currently doesn't work for me (locally to Hubitat) - I am going to reach out to their support to find out what's the deal. 
Have you seen the "pause" shade implemented anywhere?

**Comment by jbasen** [comment]
stopPositionChange does work with the shade I have for testing.  I'll change that in the code and the next time I upload a new version it will be included.  

Thanks

**Comment by micdre** [comment]
I know this issue is closed but i gave follow-up question:
What is the feedback string if i send 'stopPositionChange' ?
I can send the command from Simpl+ and it workd but i want to process the feedback.
I don't have the SImpl# sourcecode so i can not look it up.
