### ISSUE TITLE
Possible option to disable feedback on send? - Comment, Not a Issue.

### ISSUE THREAD

**Issue by GreatWhiteDan** [jbasen/Crestron-Hubitat-Integration#15]
I am struggling with using crestron devices with habitat through this module.  Maybe I am just doing it wrong, but my issue is when I turn on a dimmer for example, a DIMEX, the first thing that is sent is the full on digital signal, which sends to habitat and turns a virtual device on.  Imediatly a ramp of the analog level starts, and the first value sent is 0d, since the light was off.   Hubitat receives this, sets the virtual device to 0% and then repeats it back to crestron on the FB, which goes back to the DIMEX and sets 0d to the light which turns the light off.

What I am trying to do is set the virtual dimmer in Hubitat to the Crestron status, dimmer level, however since the Hubitat module passed the feedback immediately back, anything I try to do just gets repeated back immediately.

Is there an option to disable feedback on the Hubitat module?  If it sends a value, it should not be receiving the same value back as feedback. 

I have found ways around this.  For example, I use an analog buffer when the light is turned on to old the last analog value and not send it until it is done ramping.   There has to be an easier way.   

This all makes sense if all the devices are in habitat and reporting back to Crestron on status or levels, but when the device is crestron and we are tying to sync to habitat to use crestron in habitat, I just keep running in circles and fighting the immediate feedback.

Thanks,

**Comment by jbasen** [comment]
Hi @GreatWhiteDan 
I understand what you are trying to do but it wasn't really what I designed the software to do.  The software was designed with the idea of allowing inexpensive IoT devices to be used in a Crestron system.  The idea was always to make the Crestron processor the master (containing the smart home logic) and to use the Hubitat as a gateway to the IoT world.  I never considered the idea of trying to coordinate a mix of Crestron lights and lights connected to the Hubitat.

All that being said there isn't a reason you can't do what you want.  However, what you need to know is that from my experience trying to force ramping dim levels across the link between the Crestron system and the Hubitat is going to cause problems.  The link will become overwhelmed.  I went into this in the article I wrote for Residential Tech Today that was published when I first released the software.  You can find that article here: 

https://restechtoday.com/integrating-a-wide-range-of-zigbee-z-wave-and-iot-devices-with-crestron/

So, the approach you are taking to block the ramping analog value until it stabilizes and then trigger a light on the Hubitat side is a decent approach.  That not only solves the problem you have run into but will also keep things working smoothly as your system scales.  

An alternative would just be to mirror the inputs to you DIMEX and send them directly to the hubitat dimmer module.  If you send an on command to the DIMEX then send it to the Hubitat Dimmer Module.  If you send a 50% dim value to one, send it to both.  Again, the way this was designed to work was to keep the intelligence in the Crestron system and it will minimize the traffic between the 2 systems.  

Hope this helps

**Comment by GreatWhiteDan** [comment]
Thank you so much for responding, I appreciate it.  That makes total sense, and I plan on doing exactly what you designed it for, so again thank you for the well-designed software.   I will build around it for the few I want to sync back to Hubitat.  Keep up the good work.

**Comment by jbasen** [comment]
Thanks
