### ISSUE TITLE
Some Child Devices do not Report Events (no feedback)

### ISSUE THREAD

**Issue by ZippoD** [jbasen/Crestron-Hubitat-Integration#16]
Hi Jay,
I have discovered another issue, but not sure if this is Crestron module or Hubitat thing. 

In case you are not familiar, there are certain devices in Hubitat world that have a parent and child separation. For example, multi output relay (single device, with 4 relay outs) will be 1 parent (the device) and 4 child devices (relays 1-4). Hubitat maker API will give me each the parent and the child device ID, so the children are addressable thru the Maker API and I can control them. 

However, there is no unsolicited feedback to MakerAPI/Crestron (manual refresh does work), but there is to Hubitat. I noticed that in the Hubitat Event log for each child, there is a missing MakerAPI (eventHandler) like there would be for a "normal" device. 

Here is the twist. Some parent/child devices do work and do send eventHandler. I have one Z-wave and one (and only) Zigbee switch that reports child events. The rest that don't are all Z-wave (Plus, so they do report in side Hubitat). Any idea what might be happening? I am suspecting it is something in the Hubitat drivers, but the devices I have use built in drivers and I can't poke in their code (unless you know how). 

One more thing, one of the devices, a Qubino relay/switch (parent) with built in temperature reporting (child) does log it's temperature to Hubitat apps as "allHandler" instead of "eventHandler".
![image](https://user-images.githubusercontent.com/71191392/221379036-77373119-8328-4829-ad66-9d41281ba85d.png)
![image](https://user-images.githubusercontent.com/71191392/221378772-d0f77106-e52b-4ed3-9e95-9fd722a74882.png)

**Comment by jbasen** [comment]
Hi @ZippoD ,

Yes I have worked with some parent child devices.  For example, I have a module for multi-sensors where there are sensors for temp, humidity, vibration, etc. in one device. 

I can look at doing this for relays if you want to send me the json to turn each relay in the device on/off, the json returned when you poll for status, and the unsolicited json sent back when the status of a relay changes.

However, for devices that do not return unsolicited json there really isn't anything I can do about that.  I would try reporting the issue on the Crestron community site and see if you can get any action there.

All that being said, if I need a relay in my own home I would use one from Shelly.  Inexpensive, WiFi, high quality, full feedback, and I have a full driver set for communicating directly with almost every different Shelly device.

Thanks

**Comment by ZippoD** [comment]
"I would try reporting the issue on the Crestron community site" 
Did you mean Hubitat community site?

**Comment by jbasen** [comment]
Sorry, yes.  Hubitat community site

**Comment by ZippoD** [comment]
Can you shed some more light how the Maker API integration work so I can formulate my question properly?

I did find this comment by an ambassador there on a similar discussion. He claims all events are sent to maker API. Does your module subscribe to all events (I am only guessing here, as I have not read the documentation).

https://community.hubitat.com/t/maker-api-missing-subscription-to-device-events/57799/4?u=user2850

**Comment by jbasen** [comment]
There is no fancy subscription model for the maker API.  There is just a post url in the maker api configuration page where you had to enter an url with the IP address and the port number that the hubitat code listens to.  Then all unsolicited maker api messages with json that includes all the device feedback info are simply sent to that post feedback url.  

Hope this makes sense

Jay

**Comment by ZippoD** [comment]
Well, this one was weird. As I was doing a workaround (virtual states/variables) all devices that were not reporting FB previously started working on their own. So definitely a Hubitat bug.

Same sensor as before
![image](https://user-images.githubusercontent.com/71191392/221384408-4e0998d2-e784-4999-a8ad-fcd56901bd38.png)

**Comment by jbasen** [comment]
Great News.  As I said previously

I can look at adding support for mulit-relays if you want to send me the json to turn each relay in the device on/off, the json returned when you poll for status, and the unsolicited json sent back when the status of a relay changes.

You can capture some of this by going to the Hubitat Comm Module and setting the startup debug message output parameter to console.  Reload your program and you should be able to capture the json and other information in a toolbox console window (I find the console window does a better job of capturing that information than simpldebugger).  

Thanks

**Comment by ZippoD** [comment]
I gave the relays as an example as I thought would be the easiest to understand, but I actually don't have any.
If I do run across a device type without handles, I will let you know. 

Btw, what kind of shades are you using with Hubitat (or Crestron or even Bond)? Looking for something wallet friendly (retrofit) but stable connection.

**Comment by jbasen** [comment]
I have a Graber shade integrated with my hubitat and some e-wands.  The Graber is very high quality and I use the software I wrote to open/close a shade based on the angle / elevation of the sun.  The e-wands are on blinds that don't get used very much.

My personal opinion is not to invest in something as pricy as shades until these companies start implementing Matter and Hubitat supports it too.  I'm starting to evaluate some early Matter products and it seems to work very well.  It is just going to take a little time before it builds Momentum and pretty much everyone goes in that direction.  Since blinds are a long term investment I think it makes sense to wait a little. 

Hope this helps

Jay

**Comment by ZippoD** [comment]
So this problem is back with a new device (does have children) and I am narrowing it down. I am not sure if it has anything to do with child devices, but here is what I have found out.

If I am reading it correctly, Crestron has to "add" new subscriptions for every device. And sure enough, when I checked in the MakerAPI-> settings (gear top right corner) -> events (or direct link http://IP_address/installedapp/events/1 , where "1" equals installed app ID) - the newly added devices (3 children) have no events listed, but they should. 

I am going to start reading the actual API documentation, but you may beat me to it. Here is the comment that let me to this conclusion:
https://community.hubitat.com/t/maker-api-missing-subscription-to-device-events/57799/11?u=user2850

I don't know exactly how I triggered the subscriptions to be added last weekend. I've tried a few things and so far no luck. I definitely did not change the token ID. Possibly, adding a virtual switch last weekend is what refreshed that event subscription list. I can try it, unless you want to troubleshoot/capture something else first.

**Comment by jbasen** [comment]
First,  have you rea the article I wrote on all this for Residential Tech [Today 

](https://restechtoday.com/integrating-a-wide-range-of-zigbee-z-wave-and-iot-devices-with-crestron/)

it provides detailed instructions on making it work.

second, you say there is a problem with a new device and then you don’t even tell me what the device is.  How do you expect me to provide any kind of response

**Comment by ZippoD** [comment]
I haven't had a chance to read your article yet - hopefully tomorrow. The device is newly added to MakerAPI/Crestron, not new as newly released. It is a power strip.
I don't think that matters, as last weekend the similar issue was with 2 different types of devices. The 2 things in common between all 3 so far (other than newly added to Maker API) are:
all 3 are Z-wave
all 3 have child devices

I believe the key to all this is the lack of event subscription on the MakerAPI event settings page. I thought this might be enough hint for you. I will continue debugging this weekend and provide as much details as I can.

**Comment by jbasen** [comment]
Make and model of power strip please

**Comment by ZippoD** [comment]
It is irrelevant, as I am using built in "Generic Z-Wave Plus MultiSwitch" driver and json shows regular switch capability (using your switch v3.0). 

Well, this morning, with zero interaction my end, the event subscriptions were populated on the Hubitat end and feedback is working. I had debugger running all night - no changes evolving this device. Bummer.

**Comment by jbasen** [comment]
If you send me the following I’ll see what I can do to add support for your power strip

1)	Go to your browser and execute the following command.  You’ll need to fill in the 
IP address of your hub, the ID of the Maker API app, the Maker API device ID of 
your power strip, and your Access token

http://[Hub IP]/apps/api/[Maker App ID]/devices/[Device ID]?access_token=[OAUTH Access Token]

Send me the returned JSON

2)	Change the Startup Debug Msg Output parameter on the Hubitat Comm Manager module to "Console",
compile and upload your program to your processor.  After the program has stabilized, open a 
toolbox console window.  Using the hubitat web interface or the hubitat app, turn on, and then off,
each outlet on your power strip in some logical order.  Copy the contents of the messages displayed
in the console window and send that to me.

3) Using the web interface to your hubitat hub, navigate to the page where you can control your 
power strip.  Take a screen shot of that page and send it to me.

Thanks

**Comment by ZippoD** [comment]
Power strip is working now Jay (one more time, the device type is just a switch, last week was a switch and temperature sensor). I am sorry if I am not able to explain properly what the problem is/was. Hopefully you will experience the same one day, when you add a new device, and see with your own eyes.

**Comment by jbasen** [comment]
Thanks for letting me know
