### ISSUE TITLE
Shades Stop and Feedback

### ISSUE THREAD

**Issue by micdre** [jbasen/Crestron-Hubitat-Integration#17]
I use the Shade module which i modified and have a question:

What is the feedback string if i send 'stopPositionChange' ?
I can send the command from Simpl+ and it works but i want to process the feedback.
I don't have the C# sourcecode so i can not look it up.

**Comment by jbasen** [comment]
1) set the Startup_Debug_Msg_Output parameter on the Hubitat Comm Module to "Console"
2) Make sure you have Hubitat Shade Module in your program that corresponds with the shade you are going to test with
3) Compile and Upload the program
4) Open Crestron Toolbox and a Console Window.
5) Start your shade moving
6) Issue the stopPositionChange command
7) The code will display the json message sent by the Maker API app (if it actually sends one) in the console window.  You can also do this with SimplDebugger but SimplDebugger doesn't always display messages properly while the Console window does

**Comment by micdre** [comment]
It seems that there's is feedback from the API when i send 'stopPositionChange'. But not the one i was hoping for.
![Dump](https://user-images.githubusercontent.com/27274724/231835509-74210e3d-aca6-4be0-bf16-3853feb990b9.png)

**Comment by micdre** [comment]
Resume: The Tuya AM43 does not send a Stop feedback when a StopPositionChange is send to the unit.

**Comment by jbasen** [comment]
Hi @micdre 
Please paste the text from text console here and not a screen shot.  Unfortunately, I can't read the text in the screen shot.
Thanks
