### ISSUE TITLE
Missing Manual Poll

### ISSUE THREAD

**Issue by ZippoD** [jbasen/Crestron-Hubitat-Integration#2]
Hi there, 
Testing out this awesome module. I am also new to Hubitat. I was some [older] devices may not report FB to hub and have to be polled instead. There is away to auto poll them in Hubitat every so many seconds. But I think it will be way more efficient if we can poll from Crestron (for example on page flip). Is this something that could be added (either on per device or groups). Thanks.

**Comment by jbasen** [comment]
Hi @ZippoD 

That is a good idea and I'll work at adding it as my time allows.  However, I believe you can actually add it yourself for the specific devices you want as I think it only requires a modification to the S+ modules.  Adding in the following should work, though I haven't tested it:
```
DIGITAL_INPUT Refresh;

THREADSAFE PUSH Refresh
{
	Trace("Hubitat Device Name-EventHandler-Refresh\n");
	if (Startup_Lock = 2)
	{
		myHubitat.Send_Device_Command("command", "refresh", "", itoa(Device_ID));
	}
}
```
I hope this helps

Thanks

**Comment by ZippoD** [comment]
Indeed it deed worked. Thank you! I will have a Smartthings hub to give away soon. Let me know if you need it for something.

**Comment by jbasen** [comment]
Glad it worked.  I've started on updating all the modules to add the same functionality.  It may not really be needed for all of them but as long I'm doing an update I'm making sure that there won't be a need down the road.

I have my own old SmartThings hub sitting on a shelf :-)  But thanks for the offer.

**Comment by ZippoD** [comment]
> o

Cool. For your documentation, that should be needed for most Z-Wave (none Plus) devices. I just learned this week that someone was owning a patent for this. Platforms like ST were doing hidden poll every so many seconds in the background to resolve this. 

Another small note about you documentation:

> _iii.	The communications port you specified in step 7_
^ This really doesn't make much sense. But I did leave it as default (9000). I assume it is the inbound port on the processors that is being opened, and not the Hubitat.

**Comment by jbasen** [comment]
The software sets up a TCP/IP server on the crestron processor at that port.  It then tells the Hubitat to send messages to that port with any device updates, such as data updates from sensors.  The default of 9000 works fine but I allowed people to change it in case they are already use port 9000 for something else.  Hopefully this clears it up

**Comment by jbasen** [comment]
I've uploaded a new version 2 of the code that now supports a refresh input on modules as well as a parameter that can be set to automatically perform a refresh any time a command is sent.
