### ISSUE TITLE
Crestron Compiler Issues

### ISSUE THREAD

**Issue by soundmanmiked** [jbasen/Crestron-Hubitat-Integration#3]
I am getting compiler errors on the Crestron side with the v2.1 modules. It occurs in the event handlers for a missing ")". Is there something I am missing?

Thanks for the great work!

Mike

![Screen](https://user-images.githubusercontent.com/59380123/94837659-8a236600-03e2-11eb-99c9-d1f3e1e06708.jpg)

**Comment by jbasen** [comment]
Thanks for the image.  Can you please validate that you copied the updated hubitat.clz file to the directory you've specified in your include path.  In v2.1 there is an extra parameter in the Send_Device_Command call.  It won't compile properly with the old hubitat.clz.  Let me know if this fixes the problem for you.  Thankjs

**Comment by soundmanmiked** [comment]
That makes sense, I didn't think of that. That was the problem. 
Thanks for the quick response!

**Comment by ZippoD** [comment]
I am having the same issue - I did add the new Hubitat.clz (checked 5 times). I am still running older than 200 version database and noticed you have moved to 200+. I wonder if this is causing issue as well.

**Comment by jbasen** [comment]
There shouldn’t be an issue with the older version of the database.  I don’t use newtonsoft, which is the primary culprit of old vs new database issues.

However the only reason that this error can occur is if there is a mismatch between the version of the clz file and the version of the s+ files.  It could be there’re are multiple hubitat clz files on your computer and one is taking precedence over another. Or, you have the latest clz file but the older s+ files or vice versa.  As I said, one way or another there is a mismatch in versions.

**Comment by ZippoD** [comment]
You were correct. I was expecting the compiler to grab the file from the explicit directory. It turns out it was using the old one from my user modules folder.

**Comment by jbasen** [comment]
I’m glad the problem is resolved. 

Thanks for letting me know
