### ISSUE TITLE
Request/Discussion: Switch Double Tap FB

### ISSUE THREAD

**Issue by ZippoD** [jbasen/Crestron-Hubitat-Integration#4]
Hi There,
Wonderful work with this module. Since Hubitat is supporting double taps on system wide level, is it possible to include FB for when a switch was physically double tapped? I know I can solve it by adding a virtual switch just for the double tap and read it's FB but it will be cleaner if it is all in one place. Thanks.

**Comment by jbasen** [comment]
I will leave this open and try to make some time to investigate if Hubitat will allow me to support double click feedback. I just can’t promise it will be in the near term as I’m in the middle of trying to write 4 new Crestron drivers that I’ll be posting here over the next few weeks along with Residential Tech Today articles that go along with them. Sorry I can’t make it happen sooner

**Comment by ZippoD** [comment]
You don't have to apologize. Let me know if you need any help (although I can't do S# yet). I besides switches, dimmers and probably buttons have the double tap functionality. There might be more.

**Comment by jbasen** [comment]
Hi,  Sorry this has taken so long.  I finally had some time and have been working on adding both double-tap and held support to switches and dimmers.  Not only am I not aware of any other devices (other than buttons) that support double tap and held but I can't even find any information on support for switches and dimmers with these capabilities.  I know you only asked about double tap but a "held" button is related so I figured I would add that while I was there.   

As I said, I can't find any information on these capabilities for switches and dimmers and, to make matters worse, I don't have anything to test with.  So, I'm going to need some help testing before I simply upload it to GitHub.  Please send me an email to jay.m.basen@gmail.com and I'll send you a dropbox link where you can download a new version that you can test with.  

Thanks

**Comment by ZippoD** [comment]
You can send it here and I will test it this week. Thanks.

**Comment by jbasen** [comment]
I sent an email, including a dropbox download link, to what I think is your email address.  Please let me know if that email reaches you.  I just didn't want a test version of the code floating around in the wild that might cause people to have unnecessary issues with the code.  Thanks

**Comment by jbasen** [comment]
I've uploaded version 3.1 which now supports double-tap and press-hold events for switches and dimmers
