### ISSUE TITLE
Comms port?

### ISSUE THREAD

**Issue by TooUnCool** [jbasen/Crestron-Hubitat-Integration#7]
Hi Jay, as ever thank you for this absolute gem. I read your article and, having tried to use the Crestron-ST integration (and having contributed to the motion sensor code) I totally agree that Hubitat is miles ahead in terms of its ability to facilitate integration with Crestron. 

One small thing from the instruction, in step 14 you mention a communication port having been setup in step 7, but there is no mention of it in 7. I assumed the module is behaving in a similar way to a TCP/IP client and forwarded port 9000 to the IP of my processor and all is working fine, but thought I would mention this in case you wanted to update the instructions.

This module opens up integration with a plethora of devices that would have required complex and time consuming SIMPL# code or multiple hubs and middleware. A game changer.

Marc

**Comment by jbasen** [comment]
Thanks for pointing that out Marc.  At one point there was an issue that I couldn't programmatically set the PostURL field of the Hubitat Maker API and the Readme instructions reflected that.  When I added the ability to automatically set the PostURL field I missed removing the reference in step 14 to the old instructions.  That has now been fixed.  Thanks again
