### ISSUE TITLE
Can't find the S# sourcecode.

### ISSUE THREAD

**Issue by micdre** [jbasen/Crestron-Hubitat-Integration#8]
Hi,

First. Thanks for your exelent work!  
I can't find the full S# source code as you mensioned in your 'readme.md'

Kind regards, Michel

**Comment by jbasen** [comment]
Thanks Michel.  The Hubitat code is offered as shareware.  So it is free for personal use but there is a small licensing fee if a programmer or dealer uses it for profit on customer systems.  Unfortunately, only people who pay the licensing fee are provided with the full S# source code.  It is one of the few incentives I can offer to do that.  Thanks again.
